"""Initial schema

Revision ID: cca0e53bbba2
Revises: 
Create Date: 2026-05-17 13:14:44.521140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cca0e53bbba2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('queue',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('operation_id', sa.String(), nullable=True),
    sa.Column('module', sa.String(), nullable=True),
    sa.Column('phase', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('rollback_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_id')
    )
    op.create_table('rollback_registry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('rollback_id', sa.String(), nullable=True),
    sa.Column('operation_id', sa.String(), nullable=True),
    sa.Column('module', sa.String(), nullable=True),
    sa.Column('rollback_type', sa.String(), nullable=True),
    sa.Column('rollback_payload', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rollback_id')
    )
    op.create_table('state_locks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('resource_id', sa.String(), nullable=True),
    sa.Column('lock_holder', sa.String(), nullable=True),
    sa.Column('acquired_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_id')
    )
    op.create_table('telemetry_journal',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('metric_name', sa.String(), nullable=True),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('tags_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telemetry_journal')
    op.drop_table('state_locks')
    op.drop_table('rollback_registry')
    op.drop_table('queue')
    # ### end Alembic commands ###
